### ISSUE TITLE
Warning issued during startup for the tell script

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/GooeyJr#24]
Not sure if it means messages will fail to persist between restarts or something. Log snippet:

```
2016-12-19T02:13:28.830449+00:00 app[web.1]: [Mon Dec 19 2016 02:13:28 GMT+0000 (UTC)] ERROR ReferenceError: localstorage is not defined
2016-12-19T02:13:28.830453+00:00 app[web.1]:   at Listener.callback (/app/scripts/tell.coffee:102:5, <js>:94:29)
2016-12-19T02:13:28.830454+00:00 app[web.1]:   at executeListener (/app/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
2016-12-19T02:13:28.830454+00:00 app[web.1]:   at allDone (/app/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
2016-12-19T02:13:28.830455+00:00 app[web.1]:   at /app/node_modules/hubot/node_modules/async/lib/async.js:274:13
2016-12-19T02:13:28.830455+00:00 app[web.1]:   at Object.async.eachSeries (/app/node_modules/hubot/node_modules/async/lib/async.js:142:20)
2016-12-19T02:13:28.830456+00:00 app[web.1]:   at Object.async.reduce (/app/node_modules/hubot/node_modules/async/lib/async.js:268:15)
2016-12-19T02:13:28.830456+00:00 app[web.1]:   at /app/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
2016-12-19T02:13:28.830457+00:00 app[web.1]:   at process._tickCallback (node.js:458:13)
```

Might be of interest to @iojw

**Comment by mjuvekar7** [comment]
Fixed in #25
